// Copyright 2024 George Norton (@george-norton)
// SPDX-License-Identifier: GPL-2.0-or-later

// #define MAXTOUCH_BOOTLOADER_GESTURE

#undef MXT_GAIN
#define MXT_GAIN 10
#undef MXT_TOUCH_THRESHOLD
#define MXT_TOUCH_THRESHOLD 20
#undef MXT_TOUCH_HYST
#define MXT_TOUCH_HYST 10
#undef MXT_INTERNAL_TOUCH_THRESHOLD
#define MXT_INTERNAL_TOUCH_THRESHOLD 10
#undef MXT_INTERNAL_TOUCH_HYST
#define MXT_INTERNAL_TOUCH_HYST 5

#undef MXT_IDLE_SYNCS_PER_X
#define MXT_IDLE_SYNCS_PER_X 0
#undef MXT_ACTIVE_SYNCS_PER_X
#define MXT_ACTIVE_SYNCS_PER_X 0
#undef MXT_T56_SHIELDLESS_ENABLE
#undef MXT_T65_LENS_BENDING_ENABLE
#undef MXT_LOW_PASS_FILTER_COEFFICIENT
#define MXT_LOW_PASS_FILTER_COEFFICIENT 0
#undef MXT_CHARGE_TIME
#define MXT_CHARGE_TIME 0
#undef MXT_RETRANSMISSION_COMPENSATION_ENABLE
#define MXT_RETRANSMISSION_COMPENSATION_ENABLE 0

#define MXT_CONFTHR 5 // Increase debounce time
#define MXT_MOVE_HYSTERESIS_NEXT 16